apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: convert-to-jp-pint-peppol-from-dpfm-invoice-document
  name: convert-to-jp-pint-peppol-from-dpfm-invoice-document
spec:
  replicas: 1
  selector:
    matchLabels:
      run: convert-to-jp-pint-peppol-from-dpfm-invoice-document
      app: ORDERS
  template:
    metadata:
      labels:
        run: convert-to-jp-pint-peppol-from-dpfm-invoice-document
        app: ORDERS
    spec:
      hostname: convert-to-jp-pint-peppol-from-dpfm-invoice-document
      containers:
        - name: convert-to-jp-pint-peppol-from-dpfm-invoice-document
          image: latonaio/convert-to-jp-pint-peppol-from-dpfm-invoice-document
          imagePullPolicy: Always
          env:
            - name: "RMQ_QUEUE_FROM"
              value: "convert-to-jp-pint-peppol-from-dpfm-invoice-document-queue"
            - name: "RMQ_QUEUE_TO"
              value: "convert-to-jp-pint-peppol-from-dpfm-invoice-document-queue"
            - name: "RMQ_SESSION_CONTROL_QUEUE"
              value: "data-platform-api-orders-creates-session-control-queue"
            - name: "DB_NAME"
              value: "DataPlatformMastersAndTransactionsMysqlKube"
          envFrom:
            - configMapRef:
                name: env-config
            - secretRef:
                name: env-secret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: convert-to-jp-pint-peppol-from-dpfm-invoice-document
  name: convert-to-jp-pint-peppol-from-dpfm-invoice-document
spec:
  selector:
    run: convert-to-jp-pint-peppol-from-dpfm-invoice-document
  type: NodePort
  ports:
    - name: api
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30748
